/*
 * Copyright 2026 Robson Kades
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.github.robsonkades.fletch;

import javax.lang.model.SourceVersion;
import java.io.IOException;
import java.lang.reflect.Modifier;
import java.nio.charset.StandardCharsets;
import java.nio.file.AtomicMoveNotSupportedException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.Base64;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.TreeMap;

/**
 * Optional build tool that emits Java 17 element/attribute dispatch for a DSL mapping.
 * This artifact is not needed by the generated code at runtime.
 */
public final class XmlCodegen {
    private static final String HEADER = "// Generated by Fletch XmlCodegen v1. DO NOT EDIT.\n";
    private static final String ARGUMENTS = "Usage: XmlCodegen <public.Factory#method> <package.GeneratedClass> <source-root>";
    private static final int STATES_PER_METHOD = 32;

    private XmlCodegen() {}

    /**
     * Runs a public static no-argument mapping factory and writes a generated source file.
     * The factory executes trusted application code at build time; it must be deterministic.
     * An existing hand-written file is never replaced.
     * @param args factory, generated class name and generated-source directory
     * @throws Exception if the factory, generation or output fails
     */
    public static void main(final String[] args) throws Exception {
        if (args.length != 3) throw new IllegalArgumentException(ARGUMENTS);
        final int separator = args[0].indexOf('#');
        if (separator <= 0 || separator == args[0].length() - 1
                || args[0].indexOf('#', separator + 1) >= 0) throw new IllegalArgumentException(ARGUMENTS);
        validateName(args[1]);
        final Class<?> factory = Class.forName(args[0].substring(0, separator));
        final var method = factory.getMethod(args[0].substring(separator + 1));
        if (!Modifier.isPublic(factory.getModifiers()) || !Modifier.isStatic(method.getModifiers())
                || method.getReturnType() != XmlMapping.class) {
            throw new IllegalArgumentException("Factory must be public static, take no arguments and return XmlMapping");
        }
        final XmlMapping<?> mapping = (XmlMapping<?>) Objects.requireNonNull(method.invoke(null), "Factory returned null");
        write(mapping, args[1], Path.of(args[2]));
    }

    /**
     * Returns deterministic Java source; the mapping is not modified or extracted from.
     * @param mapping definition built using the DSL
     * @param className qualified generated class name, outside the core package
     * @return Java 17 source with a static {@code mapping(definition)} factory
     */
    public static String generate(final XmlMapping<?> mapping, final String className) {
        Objects.requireNonNull(mapping, "mapping");
        validateName(className);
        if (mapping.transBase.length > 1024 || mapping.blob.length > 1024 * 1024) {
            throw new IllegalArgumentException("Codegen prototype supports at most 1024 states and 1 MiB of names");
        }
        for (int state = 0; state < mapping.transBase.length; state++) {
            if (mapping.transCount[state] > 256 || mapping.attrCount[state] > 256) {
                throw new IllegalArgumentException("Codegen prototype supports at most 256 names per state");
            }
        }
        final int split = className.lastIndexOf('.');
        final String simple = className.substring(split + 1);
        final StringBuilder source = new StringBuilder(8192);
        source.append(HEADER).append("package ").append(className, 0, split).append(";\n\n")
                .append("public final class ").append(simple)
                .append(" extends io.github.robsonkades.fletch.XmlMappingCode {\n")
                .append("    private static final byte[] NAMES = names();\n")
                .append("    private static final ").append(simple).append(" INSTANCE = new ").append(simple).append("();\n\n")
                .append("    private ").append(simple).append("() { super(\"")
                .append(XmlMappingCode.fingerprint(mapping)).append("\"); }\n\n")
                .append("    public static <T> io.github.robsonkades.fletch.XmlMapping<T> mapping(\n")
                .append("            io.github.robsonkades.fletch.XmlMapping<T> definition) {\n")
                .append("        return INSTANCE.bind(definition);\n    }\n\n");
        appendNames(source, mapping.blob);
        appendMatcher(source, "transition", mapping.transBase, mapping.transCount,
                mapping.transHash, mapping.transTarget, mapping.transNameOff, mapping.transNameLen);
        appendMatcher(source, "attribute", mapping.attrBase, mapping.attrCount,
                mapping.attrHash, mapping.attrField, mapping.attrNameOff, mapping.attrNameLen);
        return source.append("}\n").toString();
    }

    /**
     * Writes a source file under the specified root. Identical output is left untouched;
     * changed output replaces only a file bearing this generator's header.
     * @param mapping mapping definition
     * @param className qualified generated class name
     * @param sourceRoot generated-source directory
     * @return the generated file
     * @throws IOException if output cannot be written or a hand-written file exists
     */
    public static Path write(final XmlMapping<?> mapping, final String className, final Path sourceRoot) throws IOException {
        final String source = generate(mapping, className);
        final Path root = sourceRoot.toAbsolutePath().normalize();
        final Path output = root.resolve(className.replace('.', '/') + ".java");
        if (Files.exists(output)) {
            final String old = Files.readString(output, StandardCharsets.UTF_8);
            if (old.equals(source)) return output;
            // Git may check generated sources out with Windows line endings.
            if (!old.startsWith(HEADER) && !old.startsWith(HEADER.replace("\n", "\r\n"))) {
                throw new IOException("Refusing to replace hand-written source: " + output);
            }
        }
        Files.createDirectories(output.getParent());
        final Path temporary = Files.createTempFile(output.getParent(), ".fletch-codegen-", ".java.tmp");
        try {
            Files.writeString(temporary, source, StandardCharsets.UTF_8);
            try { Files.move(temporary, output, StandardCopyOption.REPLACE_EXISTING, StandardCopyOption.ATOMIC_MOVE); }
            catch (AtomicMoveNotSupportedException unsupported) {
                Files.move(temporary, output, StandardCopyOption.REPLACE_EXISTING);
            }
        } finally { Files.deleteIfExists(temporary); }
        return output;
    }

    private static void validateName(final String name) {
        Objects.requireNonNull(name, "className");
        final int split = name.lastIndexOf('.');
        if (split <= 0 || !SourceVersion.isName(name, SourceVersion.RELEASE_17)
                || Set.of("var", "record", "yield", "sealed", "permits").contains(name.substring(split + 1))
                || name.startsWith("java.") || name.substring(0, split).equals("io.github.robsonkades.fletch")) {
            throw new IllegalArgumentException("Use a qualified Java class name in an application package: " + name);
        }
    }

    private static void appendNames(final StringBuilder source, final byte[] names) {
        final String encoded = Base64.getEncoder().encodeToString(names);
        source.append("    private static byte[] names() {\n        StringBuilder encoded = new StringBuilder(")
                .append(encoded.length()).append(");\n");
        // Chunks remain below the class-file UTF-8 constant limit, without constant folding.
        for (int offset = 0; offset < encoded.length(); offset += 8192) {
            source.append("        encoded.append(\"").append(encoded, offset, Math.min(offset + 8192, encoded.length()))
                    .append("\");\n");
        }
        source.append("        return java.util.Base64.getDecoder().decode(encoded.toString());\n    }\n\n");
    }

    private static void appendMatcher(final StringBuilder source, final String method, final int[] bases,
                                      final int[] counts, final long[] hashes, final int[] targets,
                                      final int[] offsets, final int[] lengths) {
        final Map<Integer, List<Integer>> blocks = new TreeMap<>();
        for (int state = 0; state < bases.length; state++) {
            if (counts[state] != 0) blocks.computeIfAbsent(state / STATES_PER_METHOD, ignored -> new ArrayList<>()).add(state);
        }
        source.append("    @Override\n    protected int ").append(method)
                .append("(int state, long hash, byte[] input, int offset, int length) {\n")
                .append("        switch (state >>> 5) {\n");
        for (final int block : blocks.keySet()) {
            source.append("            case ").append(block).append(": return ").append(method).append("Block").append(block)
                    .append("(state, hash, input, offset, length);\n");
        }
        source.append("            default: return -1;\n        }\n    }\n\n");
        for (final var block : blocks.entrySet()) {
            source.append("    private static int ").append(method).append("Block").append(block.getKey())
                    .append("(int state, long hash, byte[] input, int offset, int length) {\n        switch (state) {\n");
            for (final int state : block.getValue()) {
                source.append("            case ").append(state).append(": return ").append(method).append("State").append(state)
                        .append("(hash, input, offset, length);\n");
            }
            source.append("            default: return -1;\n        }\n    }\n\n");
        }
        for (int state = 0; state < bases.length; state++) {
            if (counts[state] == 0) continue;
            source.append("    private static int ").append(method).append("State").append(state)
                    .append("(long hash, byte[] input, int offset, int length) {\n");
            final Map<Integer, List<Integer>> buckets = new TreeMap<>();
            for (int i = bases[state]; i < bases[state] + counts[state]; i++) {
                buckets.computeIfAbsent((int) (hashes[i] ^ (hashes[i] >>> 32)), ignored -> new ArrayList<>()).add(i);
            }
            if (counts[state] > 1) source.append("        switch ((int) (hash ^ (hash >>> 32))) {\n");
            for (final var bucket : buckets.entrySet()) {
                if (counts[state] > 1) source.append("            case 0x").append(Integer.toHexString(bucket.getKey())).append(":\n");
                for (final int i : bucket.getValue()) {
                    source.append(counts[state] > 1 ? "                " : "        ")
                            .append("if (hash == 0x").append(Long.toHexString(hashes[i]))
                            .append("L && length == ").append(lengths[i])
                            .append(" && java.util.Arrays.equals(NAMES, ").append(offsets[i]).append(", ")
                            .append(offsets[i] + lengths[i]).append(", input, offset, offset + length)) return ")
                            .append(targets[i]).append(";\n");
                }
                if (counts[state] > 1) source.append("                return -1;\n");
            }
            if (counts[state] > 1) source.append("            default: return -1;\n        }\n");
            else source.append("        return -1;\n");
            source.append("    }\n\n");
        }
    }
}
